/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mymovieapp.service;


import com.mycompany.mymovieapp.model.Customer;
import com.mycompany.mymovieapp.model.Account;
import java.util.ArrayList;
import java.util.List;



public class CustomerService {
    
    public static List<Account> list = new ArrayList<>();
    
    public String createAccount(String userName, String password, boolean child){
    setAccountID(list.size() +1); //account ID should be autogenerated here
    list.add(userName, password, child);
    System.out.println("201 - new resource created: /messages/" + String.valueOf(m.getAccountID()));
    return m;
    //return String account created
    }
    
    public List<Account> getAllAccounts(){
        return list;
    }
    
    public Account getOneAccount(int id){
        return list.get(id-1);
    }
    
    
}