/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mymovieapp.service;


import com.mycompany.mymovieapp.model.Customer;
import com.mycompany.mymovieapp.model.MoviesOnDemand;
import com.mycompany.mymovieapp.model.Account;
import java.util.ArrayList;
import java.util.List;



public class CustomerService {
    
    public static List<Account> list = new ArrayList<>();
    
    Customer c = new Customer();
    MoviesOnDemand m = new MoviesOnDemand();
    
        public Customer customerByID(int custID){
        for(Customer c: m.allCustomers){
            if(custID == c.getCustID()){
            Customer = c;
        }
        }
//        else{//try to get something inside the else
//        return ("Customer does not exist"); 
//        }
        cust = c;
        }
    
    public Account createAccount(int custID, String userName, String password, boolean child){
        //call 
        //define cust with cust id add account to that cust
        Customer c = where custID=custID;
        Account account = new Account(list.size()+1, userName, password, child);
   // setAccountID(list.size() +1); //account ID should be autogenerated here
        list.add(account);
    //System.out.println("201 - new resource created: /messages/" + String.valueOf(m.getAccountID()));
        return account;//return the instance let resources render as JSON
    //return String account created
    }
    
    public List<Account> getAllAccounts(){
        return list;
    }
    
    public Account getOneAccount(int id){
        return list.get(id-1);
    }
    
    
}